### ISSUE TITLE
Docker環境のサポート追加

### ISSUE THREAD

**Issue by takuyakubo** [takuyakubo/paper-to-slides#4]
## 課題
現在のリポジトリには、Docker環境でのアプリケーション実行をサポートするための設定が含まれていません。

## 問題点
- 開発環境のセットアップが複雑になる可能性がある
- 環境間の一貫性が保証されない
- デプロイメントプロセスが複雑化する
- システム依存関係の問題が発生する可能性がある

## 改善案
以下のDockerサポートを追加することを提案します：

1. **Dockerfileの追加**
   - アプリケーションのコンテナ化
   - 必要な依存関係のインストール
   - 適切な実行環境の設定

2. **docker-compose.ymlの追加**
   - 開発環境の設定
   - データ永続化の設定
   - 環境変数の管理

3. **開発およびプロダクション用の設定分離**
   - 開発環境用の設定
   - 本番環境用の最適化設定
   - テスト環境用の設定

### Dockerfile
```dockerfile
# ベースイメージとして公式Pythonイメージを使用
FROM python:3.9-slim

# 作業ディレクトリを設定
WORKDIR /app

# 依存関係を先にコピーしてインストール（キャッシュ活用）
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# PDFライブラリの依存関係をインストール
RUN apt-get update && apt-get install -y --no-install-recommends \
    poppler-utils \
    libpoppler-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# アプリケーションコードをコピー
COPY . .

# データディレクトリを作成
RUN mkdir -p data/papers output/slides logs

# 環境変数を設定
ENV PYTHONPATH=/app \
    PYTHONUNBUFFERED=1

# アプリケーションの実行
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
```

### docker-compose.yml
```yaml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - paper_data:/app/data
      - slide_output:/app/output
      - logs:/app/logs
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    restart: unless-stopped

volumes:
  paper_data:
  slide_output:
  logs:
```

### .dockerignore
```
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg
.git/
.gitignore
.env
data/
output/
logs/
```

### 開発用ドキュメント（docs/docker-guide.md）
```markdown
# Docker 開発ガイド

## 前提条件
- Docker
- Docker Compose

## 開発環境のセットアップ

1. リポジトリをクローン：
   ```
   git clone https://github.com/takuyakubo/paper-to-slides.git
   cd paper-to-slides
   ```

2. 環境変数ファイルをコピーして編集：
   ```
   cp .env.example .env
   # .envファイルを編集して必要な環境変数を設定
   ```

3. Dockerコンテナをビルドして起動：
   ```
   docker-compose up -d
   ```

4. アプリケーションにアクセス：
   - API: http://localhost:8000
   - API ドキュメント: http://localhost:8000/docs

## コマンド一覧

- コンテナを起動：
  ```
  docker-compose up -d
  ```

- コンテナを停止：
  ```
  docker-compose down
  ```

- ログを表示：
  ```
  docker-compose logs -f app
  ```

- コンテナ内でコマンドを実行：
  ```
  docker-compose exec app python -m pytest
  ```

## プロダクション用デプロイ
プロダクション環境では、以下のコマンドでイメージをビルドします：

```
docker build -t paper-to-slides:prod --build-arg ENVIRONMENT=production .
```

実行：
```
docker run -d -p 8000:8000 --env-file .env.prod paper-to-slides:prod
```
```

これらの改善により、開発者は環境構築の手間を減らし、一貫した環境でアプリケーションの開発・テスト・デプロイメントが可能になります。
